version: '3.8'

services:
  alfred:
    restart: unless-stopped
    container_name: alfred
    image: ghcr.io/pukabyte/alfred:latest
    hostname: alfred
    user: "1000:1000" # change this to your user and group id
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - TZ=Etc/UTC
    networks: 
      - saltbox # change this to your network
    labels:
      com.github.saltbox.saltbox_managed: true
    volumes:
      - /opt/alfred:/app/data # change this to where your app data is
      - /mnt:/mnt:rslave # Change this to where your symlinks and mounted volumes are

networks:
  saltbox:
    external: true 