version: '3.8'

services:
  alfred:
    restart: unless-stopped
    container_name: alfred
    image: ghcr.io/pukabyte/alfred:latest
    hostname: alfred
    user: "1000:1000"
    environment:
      - TZ=Etc/UTC
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
    volumes:
      - /opt/alfred:/app/data
      - ${SYMLINK_DIR}:${SYMLINK_DIR}
      - ${TORRENTS_DIR}:${TORRENTS_DIR}
      - /etc/localtime:/etc/localtime:ro

networks:
  saltbox:
    external: true 